FROM docker.io/registry/image:tag

# Set the working directory
WORKDIR /app

# Copy the necessary files
COPY app.py .
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set the entrypoint command
CMD [ "python", "app.py" ]
