# Use the official Nginx base image
FROM nginx:latest

# Replace the default index.html with a custom file
RUN echo "This is Arun" > /usr/share/nginx/html/index.html

# Expose port 8080
EXPOSE 8080

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
